let restaurantList = [
    {
        id: "1013619",
        name: "Chinese Wok",
        cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/12/24/15345730-3e92-4301-8bf8-d3d327d96ce2_1013619.jpg",
        costForTwo: "₹250 for two",
        cuisines: [
            "Chinese",
            "Asian",
            "Tibetan",
            "Desserts"
        ],
        avgRating: 3.0,
        totalRatingsString: "190",
        slaString: "30-35 mins",
        lastMileTravelString: "0.7 km",
        discountInfo: "ITEMS AT  ₹129",
        veg: false,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "65797",
        name: "Leon's - Burgers & Wings ",
        cloudinaryImageId: "r4ufflqojich0r29efvc",
        costForTwo: "₹300 for two",
        cuisines: ["American", "Snacks", "Turkish", "Portuguese"],
        avgRating: 4.3,
        totalRatingsString: "10K+",
        slaString: "17 -25 mins",
        lastMileTravelString: "1.3 km",
        discountInfo: "₹125 OFF | ABOVE ₹249",
        veg: false,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "334475",
        name: "KFC",
        cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
        costForTwo: "₹400 for two",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        avgRating: 4.2,
        totalRatingsString: "1K+",
        slaString: "20-25 mins",
        lastMileTravelString: "0.5 km",
        discountInfo: "20% OFF | UPTO ₹50",
        veg: false,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "75966",
        name: "Kaati Zone Rolls & Wraps",
        cloudinaryImageId: "ibmfw10arqzrdibq03mt",
        costForTwo: "₹150 for two",
        cuisines: ["Fast Food", "Bengali", "Beverages", "Desserts"],
        avgRating: 3.5,
        totalRatingsString: "1K+",
        slaString: "20-25 mins",
        lastMileTravelString: "0.3 km",
        discountInfo: "40% OFF | UPTO ₹80",
        veg: false,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "378146",
        name: "Big Bowl",
        cloudinaryImageId: "992f217c2f122c0d8fc385855ca30722",
        costForTwo: "₹250 for two",
        cuisines: ["North Indian", "Chinese", "Tibetan"],
        avgRating: 4.1,
        totalRatingsString: "5K+",
        slaString: "18-25 mins",
        lastMileTravelString: "1.1 km",
        discountInfo: "50% OFF | UPTO ₹100",
        veg: false,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "751353",
        name: "Tim Hortons",
        cloudinaryImageId: "26c8263d346b308a6a62c003d1d9eca1",
        costForTwo: "₹400 for two",
        cuisines: [
            "Coffee",
            "Beverages",
            "Cafe",
            "Desserts",
            "sandwich",
            "Fast Food"
        ],
        avgRating: 4.4,
        totalRatingsString: "1.9K+",
        slaString: "20-25 mins",
        lastMileTravelString: "0.9 km",
        discountInfo: "50% OFF | FLAT DEAL",
        veg: true,
        hasOffers: true,
        isOpen: false,
    },
    {
        id: "108424",
        name: "Domino's Pizza",
        cloudinaryImageId: "vw6n5betlssnqelt7rmu",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
        avgRating: 4.0,
        totalRatingsString: "10K+",
        slaString: "30 mins",
        lastMileTravelString: "2.2 km",
        discountInfo: "30% OFF | UPTO ₹120",
        veg: false,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "550517",
        name: "Truffles",
        cloudinaryImageId: "m3tkgk5dbxsvhbzsaxdy",
        costForTwo: "₹400 for two",
        cuisines: ["American", "Continental", "Desserts"],
        avgRating: 4.4,
        totalRatingsString: "1K+",
        slaString: "25 mins",
        lastMileTravelString: "1.5 km",
        discountInfo: "25% OFF | ABOVE ₹299",
        veg: false,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "71206",
        name: "Biryani Blues",
        cloudinaryImageId: "kpztruxactqgf9vyf5gk",
        costForTwo: "₹400 for two",
        cuisines: ["Biryani", "North Indian", "Mughlai"],
        avgRating: 4.1,
        totalRatingsString: "5K+",
        slaString: "27 mins",
        lastMileTravelString: "2.0 km",
        discountInfo: "60% OFF | UPTO ₹120",
        veg: false,
        hasOffers: true,
        isOpen: false,
    },
    {
        id: "490508",
        name: "Baskin Robbins - Ice Cream Desserts",
        cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
        costForTwo: "₹300 for two",
        cuisines: ["Ice Cream", "Desserts"],
        avgRating: 4.3,
        totalRatingsString: "1K+",
        slaString: "15 mins",
        lastMileTravelString: "0.8 km",
        discountInfo: "30% OFF | UPTO ₹75",
        veg: true,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "311804",
        name: "NIC Ice Creams",
        cloudinaryImageId: "c8b98c4064dc2fd6bdf350212e5f0bd5",
        costForTwo: "₹120 for two",
        cuisines: ["Ice Cream", "Desserts"],
        avgRating: 4.5,
        totalRatingsString: "5K+",
        slaString: "20 mins",
        lastMileTravelString: "1.2 km",
        discountInfo: "20% OFF | ABOVE ₹149",
        veg: true,
        hasOffers: true,
        isOpen: true,
    },


    {
        id: "1046802",
        name: "Lassi shop",
        cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/3/17/803d5fcd-56fd-4393-ad45-2c6294a3b5e6_1046802.jpg",
        costForTwo: "₹120 for two",
        cuisines: [
            "Ice Cream",
            "Juices",
            "Cafe"
        ],
        avgRating: 3.1,
        totalRatingsString: "<3",
        slaString: "45-50 mins",
        lastMileTravelString: "3.5 km",
        discountInfo: "None",
        veg: true,
        hasOffers: false,
        isOpen: false,
    },
    {
        id: "596949",
        name: "Olio - The Wood Fired Pizzeria",
        cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/26/e35f38cf-8697-46f3-9d5d-cf80c6493833_596949.jpg",
        costForTwo: "₹300 for two",
        cuisines: [
            "Pizzas",
            "Pastas",
            "Italian",
            "Fast Food",
            "Snacks",
            "Beverages",
            "Desserts"
        ],
        avgRating: 3.5,
        totalRatingsString: "1.5K+",
        slaString: "50-55 mins",
        lastMileTravelString: "2.4 km",
        discountInfo: "None",
        veg: false,
        hasOffers: false,
        isOpen: true,

    },
    {
        id: "534235",
        name: "Cheesecake & Co.",
        cloudinaryImageId: "b318c0b4bc2169550145ace1d6e791a2",
        costForTwo: "₹250 for two",
        cuisines: [
            "Bakery"
        ],
        avgRating: 3.6,
        totalRatingsString: "3.2K+",
        slaString: "30-35 mins",
        lastMileTravelString: "1.0 km",
        discountInfo: "50% OFF | ABOVE ₹100",
        veg: true,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "108427",
        name: "Domino's Pizza",
        cloudinaryImageId: "vw6n5betlssnqelt7rmu",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
        avgRating: 4.0,
        totalRatingsString: "10K+",
        slaString: "30 mins",
        lastMileTravelString: "2.2 km",
        discountInfo: "None",
        veg: false,
        hasOffers: false,
        isOpen: true,
    },
    {
        id: "550510",
        name: "Truffles",
        cloudinaryImageId: "m3tkgk5dbxsvhbzsaxdy",
        costForTwo: "₹400 for two",
        cuisines: ["American", "Continental", "Desserts"],
        avgRating: 3.8,
        totalRatingsString: "1K+",
        slaString: "25 mins",
        lastMileTravelString: "1.5 km",
        discountInfo: "25% OFF | ABOVE ₹299",
        veg: false,
        hasOffers: true,
        isOpen: false,
    },
    {
        id: "71203",
        name: "Biryani Blues",
        cloudinaryImageId: "kpztruxactqgf9vyf5gk",
        costForTwo: "₹400 for two",
        cuisines: ["Biryani", "North Indian", "Mughlai"],
        avgRating: 4.1,
        totalRatingsString: "5K+",
        slaString: "27 mins",
        lastMileTravelString: "2.0 km",
        discountInfo: "60% OFF | UPTO ₹120",
        veg: false,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "490568",
        name: "Baskin Robbins - Ice Cream Desserts",
        cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
        costForTwo: "₹300 for two",
        cuisines: ["Ice Cream", "Desserts"],
        avgRating: 4.3,
        totalRatingsString: "1K+",
        slaString: "15 mins",
        lastMileTravelString: "0.8 km",
        discountInfo: "None",
        veg: true,
        hasOffers: false,
        isOpen: true,
    },
    {
        id: "311806",
        name: "NIC Ice Creams",
        cloudinaryImageId: "c8b98c4064dc2fd6bdf350212e5f0bd5",
        costForTwo: "₹120 for two",
        cuisines: ["Ice Cream", "Desserts"],
        avgRating: 4.5,
        totalRatingsString: "5K+",
        slaString: "20 mins",
        lastMileTravelString: "1.2 km",
        discountInfo: "20% OFF | ABOVE ₹149",
        veg: true,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "23682",
        name: "McDonald's",
        cloudinaryImageId: "ee5f8e06b300efc07c9fe3f4df40dfc4",
        costForTwo: "₹400 for two",
        cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
        avgRating: 4.2,
        totalRatingsString: "10K+",
        slaString: "23 mins",
        lastMileTravelString: "4.1 km",
        discountInfo: "None",
        veg: false,
        hasOffers: false,
        isOpen: true,
    },
    {
        id: "125956",
        name: "Glen's Bakehouse",
        cloudinaryImageId: "whfviizdgvwg0uwfk8dy",
        costForTwo: "₹500 for two",
        cuisines: ["Desserts", "Bakery", "Beverages", "Continental", "Italian"],
        avgRating: 4.4,
        totalRatingsString: "5K+",
        slaString: "15 mins",
        lastMileTravelString: "0.9 km",
        discountInfo: "None",
        veg: false,
        hasOffers: false,
        isOpen: false,
    },
    {
        id: "18973",
        name: "Nandhana Palace",
        cloudinaryImageId: "195876a3181ef63f76e45e3a7b49b585",
        costForTwo: "₹500 for two",
        cuisines: ["Biryani", "Andhra", "South Indian", "North Indian"],
        avgRating: 4.1,
        totalRatingsString: "10K+",
        slaString: "17 mins",
        lastMileTravelString: "0.6 km",
        discountInfo: "None",
        veg: false,
        hasOffers: false,
        isOpen: true,
    },
    {
        id: "4138",
        name: "Subway",
        cloudinaryImageId: "0bf19a82b109b40c2f5c56d00f071a33",
        costForTwo: "₹350 for two",
        cuisines: ["Fast Food", "Salads", "Healthy Food", "Desserts", "Beverages"],
        avgRating: 4.1,
        totalRatingsString: "10K+",
        slaString: "21 mins",
        lastMileTravelString: "1.9 km",
        discountInfo: "20% OFF | UPTO ₹120",
        veg: false,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "79403",
        name: "Sri Udupi Park",
        cloudinaryImageId: "tfbnpd65irvhp9iwhbtk",
        costForTwo: "₹200 for two",
        cuisines: ["South Indian", "North Indian", "Chaat", "Beverages", "Chinese"],
        avgRating: 4.4,
        totalRatingsString: "10K+",
        slaString: "23 mins",
        lastMileTravelString: "1.5 km",
        discountInfo: "₹125 OFF | ABOVE ₹299",
        veg: true,
        hasOffers: true,
        isOpen: true,
    },
    {
        id: "48207",
        name: "Kanti Sweets",
        cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/2/13/d6d1cd78-187e-4901-b140-3161b64f4121_48207.jpg",
        costForTwo: "₹150 for two",
        cuisines: ["Sweets"],
        avgRating: 4.6,
        totalRatingsString: "7.0 K+",
        slaString: "15 mins",
        lastMileTravelString: "0.7 km",
        discountInfo: "ITMS AT  ₹29",
        veg: true,
        hasOffers: true,
        isOpen: false,
    },
    {
        id: "139558",
        name: "Dindigul Thalappakatti",
        cloudinaryImageId: "exhzkyd9pjoqlobruy4v",
        costForTwo: "₹650 for two",
        cuisines: [
            "Biryani",
            "Barbecue",
            "South Indian",
            "Chinese",
            "North Indian"
        ],
        avgRating: 4.3,
        totalRatingsString: "8.7K+",
        slaString: "30-35 mins",
        lastMileTravelString: "4.1 km",
        discountInfo: "ITEMS AT ₹179 ",
        veg: false,
        hasOffers: true,
        isOpen: true,
    }

];
export default restaurantList;
